-- 3) Porcentaje de Votos [3 puntos]
-- problema porcentajeDeVotos (vice: String, formulas: seq⟨String x String⟩,votos:seq< Z >) : R {
--  requiere: {La segunda componente de algún elemento de formulas es vice}
--  requiere: {¬formulasInvalidas(formulas)}
--  requiere: {|formulas| = |votos|}|
--  requiere: {Todos los elementos de votos son mayores o iguales a 0}
--  requiere: {Hay al menos un elemento de votos mayores estricto a 0}
--  asegura: {res es el porcentaje de votos que obtuvo vice sobre el total de votos afirmativos}
-- }
-- Para resolver este ejercicio pueden utilizar la función division presentada en el Ejercicio 1.

-- parcial  simulacro
--1) 